### PR TITLE
modernizr class toggling

### PR DESCRIPTION
**Pull request by paulirish**
turning off CSS3 is really nice if you can also preview what your adaptive classes will look like

so here we take all your modernizr classes on the `<html>` tag and toggle them to their other state.  This is not exactly the same as turning them off, but we could do that as well. 

This just seemed like the right place to start.

Dig?

### CODE REVIEW

**Comment by paulirish** [comment]
### two notes, one related one not

related: marcel introduced this idea. i liked it so i did it. http://forrst.com/posts/CSS_for_removing_CSS3-z1O#comment-339099

unrelated: chris coyier has a very similar project: https://github.com/chriscoyier/CSS3-StripTease/blob/master/striptease.js

**Comment by paulirish** [comment]
now we toggle between the no- state and the real state. this matches the deCSS3 behavior.

also we wouldnt want to test like `html.touch` classes along with the IE6 assumptions... so.. this is better.

**Comment by SlexAxton** [comment]
tite

**Comment by marceltt** [comment]
Does what it says, shot @paulirish.

**Pull request merged**
